name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: MinGW
            mingw: true
            ninja: true
            cmake: -DCMAKE_TOOLCHAIN_FILE=scripts/cmake-toolchain-mingw64-i686.cmake

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: Install MinGW toolchain
        if: startswith(matrix.os, 'ubuntu') && matrix.mingw
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64 ninja-build

      - run: Setup SDL3
        uses: libsdl-org/setup-sdl@main
        with:
          cmake-arguments: ${{ matrix.cmake }}

      - run: Install ninja
        if: matrix.ninja
        uses: ./.github/actions/setup-ninja

      - run: CMake (Configure)
        run: |
          cmake -S . -B build ${{ matrix.cmake }} ${{ matrix.ninja && '-GNinja' }}

      - run: CMake (Build)
        run: |
          cmake --build build --verbose
