name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: MinGW
            mingw: true
            cmake: '-GNinja'
            cmake-toolchain-file: scripts/cmake-toolchain-mingw64-i686.cmake

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW toolchain
        if: startswith(matrix.os, 'ubuntu') && matrix.mingw
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64 ninja-build

      - name: Install ninja
        uses: ./.github/actions/setup-ninja

      - name: Setup SDL3
        uses: libsdl-org/setup-sdl@main
        with:
          version: 3-head
          cmake-generator: Ninja
          cmake-toolchain-file: ${{ matrix.cmake-toolchain-file }}

      - name: CMake (Configure)
        run: |
          cmake -S . -B build ${{ (matrix.cmake-toolchain-file && format('-DCMAKE_TOOLCHAIN_FILE={0}', matrix.cmake-toolchain-file)) || '' }} ${{ matrix.cmake  || '' }}

      - name: CMake (Build)
        run: |
          cmake --build build --verbose
